# Site settings
title: Kavish Blog
email: 
description: > # this means to ignore newlines until "baseurl:"
# Digital portal for my personal blogs and posts
baseurl: "/cyberbullying/" # the subpath of your site, e.g. /blog/
url: "https://kavish.sendildevar.in/cyberbullying/" # the base hostname & protocol for your site


exclude:
  - bower_components
  - Gemfile
  

# Build settings
markdown: kramdown
kramdown:
  input: GFM  #Github Flavored Markdown

